version: "2"

services:
  lora-packet-forwarder:
    restart: unless-stopped
    image: lora-packet-forwarder:latest
    volumes:
      - ./config:/opt/pf-config
    devices:
      - /dev/spidev1.0:/dev/spidev1.0
    dns:
      - 8.8.8.8
